sudo: required

services:
  - docker

script:
  - docker build -q -t kararha/cordhello:latest .
   # Log in to docker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kararha/cordhello:latest
  - docker run --name corb kararha/cordhello:latest /bin/sh -c "cordova build android"
  - docker cp corb:/app/platforms/android/app/build/outputs/apk/debug/app-debug.apk $TRAVIS_BUILD_DIR 

before_deploy:

  - git tag -a v0.1 -m "my version 0.1"

  
deploy:
  provider: releases
  api_key: 
    secure: $GITHUB_API_KEY
  file: "$TRAVIS_BUILD_DIR/app-debug.apk"
  skip_cleanup: true
  on:
    tags: false
    repo: kararmehdihabib/cordhello
    branch: master